import type { WatermarkConfig } from "@/types/watermark";

// CSS preview coordinates only; final raster PDF is generated by the backend.
export const CSS_PIXELS_PER_POINT = 96 / 72;
export const mmToPreviewPixels = (mm: number) => (mm * 96) / 25.4;
export interface PreviewSize {
  width: number;
  height: number;
}

export function watermarkLayout(
  config: WatermarkConfig,
  size: PreviewSize,
  textSize: PreviewSize,
  rotatedSize?: PreviewSize,
) {
  const radians = (config.angle * Math.PI) / 180;
  const rotatedWidth =
    rotatedSize?.width ??
    Math.abs(textSize.width * Math.cos(radians)) +
      Math.abs(textSize.height * Math.sin(radians));
  const rotatedHeight =
    rotatedSize?.height ??
    Math.abs(textSize.width * Math.sin(radians)) +
      Math.abs(textSize.height * Math.cos(radians));
  const padding = mmToPreviewPixels(8);
  // For oversized text, shrink only the preview mark enough to keep it inside the page.
  const fit = Math.min(
    1,
    Math.max(1, size.width - 2 * padding) / Math.max(1, rotatedWidth),
    Math.max(1, size.height - 2 * padding) / Math.max(1, rotatedHeight),
  );
  const insetX = Math.min(size.width / 2, padding + (rotatedWidth * fit) / 2);
  const insetY = Math.min(size.height / 2, padding + (rotatedHeight * fit) / 2);
  const [vertical, horizontal] = config.position.split("-");
  return {
    x:
      horizontal === "left"
        ? insetX
        : horizontal === "right"
          ? size.width - insetX
          : size.width / 2,
    y:
      vertical === "top"
        ? insetY
        : vertical === "bottom"
          ? size.height - insetY
          : size.height / 2,
    fit,
    tileWidth: Math.max(1, rotatedWidth + mmToPreviewPixels(config.spaceX)),
    tileHeight: Math.max(1, rotatedHeight + mmToPreviewPixels(config.spaceY)),
  };
}
